#配置标识,测试用
env: config1.6
spring:
  #消息总线添加rabbitmq配置,前提是先启动rabbitmq服务
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#开启所有访问，包括bus-refresh的任务
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
